Andres Mejia

Engr 114 winter 23

Q05.01, Q05.09, Q05.30, Q05.33, Q05.51, Q05.70

In [2]:
import numpy as np

In [5]:
# 5.01
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
# 5.09
b = np.linspace(0,1,18)
print(b)

[0.         0.05882353 0.11764706 0.17647059 0.23529412 0.29411765
 0.35294118 0.41176471 0.47058824 0.52941176 0.58823529 0.64705882
 0.70588235 0.76470588 0.82352941 0.88235294 0.94117647 1.        ]


In [41]:
# 5.30
b = np.arange(0,25)
print(b)
b.shape = (5,5)
print(b)

## a.
x = b[1,:]
print(x)

## b 
y = np.size(x)
print(y)

## c 
z = b[:,4]
print(z)

## d
t = b
print(t)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[5 6 7 8 9]
5
[ 4  9 14 19 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [49]:
# 5.33
F = np.array([5, -4.7, 99, 50, 6, -1, 0, 50, -78, 27, 10])

## a
gfive = F > 5
x = F[gfive]
print(x)

## b
lthirty = F < 30
gl = np.logical_and(gfive,lthirty)
y = F[gl]
print(y)

## c 
efifty = F == 50
gle = np.logical_or(gl,efifty)
z = F[gle]
print(z)


[99. 50.  6. 50. 27. 10.]
[ 6. 27. 10.]
[50.  6. 50. 27. 10.]


In [69]:
# 5.51 
angles = np.linspace(0,2*np.pi,5)
print(angles)

## a
print(np.sin(angles))

## b 
print(np.cos(angles))

## c
print(np.radians(angles))

[0.         1.57079633 3.14159265 4.71238898 6.28318531]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]
[0.         0.02741557 0.05483114 0.0822467  0.10966227]


In [78]:
## 5.70
A = np.array([[4,-2], [-6, 1]])
b = np.array([-42, 31])
c = np.linalg.solve(A, b)
print(c)

x = c[0]
y = c[1]
print(x)
print(y)

print(4*x - 2*y)
print(-6*x + y)


[-2.5 16. ]
-2.5
16.0
-42.0
31.0
