* array creation
* array indexing and slicing
* array masking
* np.where() fucntion

# Array Creation

In [1]:
# before arrays can be created, Numpy needs to be imported
import numpy as np

In [6]:
a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a,'\n')
print(b)

[1 2 3] 

[[1 2]
 [3 4]]


In [7]:
c = np.arange(-5,6,1)  # a range of numbers. start, stop, steps
print(c)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [8]:
d = np.arange(10,-11,-2)
print(d)

[ 10   8   6   4   2   0  -2  -4  -6  -8 -10]


In [9]:
f = np.linspace(-3,3,10)     # creates a linear space of numbers
print(f)

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]


In [10]:
g = np.logspace(-3,3,6)
print(g)

[1.00000000e-03 1.58489319e-02 2.51188643e-01 3.98107171e+00
 6.30957344e+01 1.00000000e+03]


# Indexing and Slicing

In [16]:
h = np.arange(-3,9,1)
print(h)
print(h.shape)
h.shape = (3,4)    # set shape to 3 row 4 column
print()

print(h.shape)
print(h)

[-3 -2 -1  0  1  2  3  4  5  6  7  8]
(12,)

(3, 4)
[[-3 -2 -1  0]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [18]:
print(h[0]) #index first element, the first row
print(h[-1]) # last row

[-3 -2 -1  0]
[5 6 7 8]


In [20]:
print(h[0:3,1])  # row 0-3(exclusive), column one
print(h[-1,1:4]) # last row, column 1-4(exclusive)

[-2  2  6]
[6 7 8]


# Masking

In [21]:
print(h)

[[-3 -2 -1  0]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [24]:
# pull out negative numbers
mask1 = h<0
print(mask1)
print(h[mask1])

[[ True  True  True False]
 [False False False False]
 [False False False False]]
[-3 -2 -1]


In [34]:
mask3 = -1<=h
print(mask3)
print(h[mask3])

mask4 = h<=6
print(mask4)
print()

mask5 = np.logical_and(mask3,mask4)
print(mask5)
print(h[mask5])

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[-1  0  1  2  3  4  5  6  7  8]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]]

[[False False  True  True]
 [ True  True  True  True]
 [ True  True False False]]
[-1  0  1  2  3  4  5  6]


# np.where

In [36]:
# find location of values
k = np.array([20,15,18,10,17,0])
print(k)

[20 15 18 10 17  0]


In [44]:
# which class day had 10 students in it
index10 = np.where(k==10)
print(index10)
print(type(index10))
print(len(index10))
print(index10[0])
print(type(index10[0]))
print(index10[0][0])
print(type(index10[0][0]))
print(index10[0][0]+1)



(array([3]),)
<class 'tuple'>
1
[3]
<class 'numpy.ndarray'>
3
<class 'numpy.int64'>
4


In [50]:
# which class days had more than 10 students in it
index_more_than_10 = np.where(k>10)
print(index_more_than_10)
print('the days with more than 10 students were', *index_more_than_10[0]+1)

(array([0, 1, 2, 4]),)
the days with more than 10 students were 1 2 3 5


In [55]:
# create tuple that contains a list that contains an array
r = ([np.array([2,3])])
print(r)
print(r[0][0]+1)

[array([2, 3])]
3
