# Numpy and Arrays

In [1]:
# built in functions to python standard library
a = 3
type(a)

int

In [2]:
print('the print functions is also built-in to python')

the print functions is also built-in to python


In [3]:
b = [1,2.2,'me']
len(b)

3

In [4]:
# some functions are part of the python standard library but not built in
# need to be imported 
sin(20)

NameError: name 'sin' is not defined

In [ ]:
from math import sin
sin(20)

In [6]:
from math import sin, cos, tan
print(sin(2))
print(cos(2))
print(tan(2))

0.9092974268256817
-0.4161468365471424
-2.185039863261519


python itself does not have numpy and pandas but anaconda comes with them

In [10]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [21]:
#import all numpy functions
import numpy as np   # good and widely used abbreviation
np.__version__  # get version number of import

'1.21.5'

# List vs Arrays

In [29]:
a = [1,2.2,'me']
print(a)
b = np.array([1,2.2,'me'])
print(b)
c = np.array([1,2,3.3])
print(c)
d = np.array([True,False,0, 0.0])
print(d)

# arrays are homogenous so makes all items into one type (least precise data type)

[1, 2.2, 'me']
['1' '2.2' 'me']
[1.  2.  3.3]
[1. 0. 0. 0.]


In [38]:
a = np.array([1,2,3])
print(a)
print(a.dtype)          # get data type
print(a.size)           # amount of objects in array
print(a.ndim)

[1 2 3]
int64
3
1


In [36]:
b = np.array([1,2,3], np.float64)
print(b)
b.dtype

[1. 2. 3.]


dtype('float64')

In [42]:
c = np.array([[1,2], [3,4]])
print(c)
c.shape                           # shape of array, rows/columns

[[1 2]
 [3 4]]


(2, 2)

In [43]:
# cast the datatype as more precise
d = np.array([1.1,0.0], np.bool)
print(d)

[ True False]


/var/folders/yk/k5d_7hg57nx8x0bm9kq7myl80000gn/T/ipykernel_26579/393158039.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  d = np.array([1.1,0.0], np.bool)


In [48]:
# np.arange
b = np.arange(0,11,1)   #start, stop(exclusive), step
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [45]:
b = np.arange(0,11)    #default step 1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
b = np.arange(11)    # default start 0, default step 1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
#np.linspace
c = np.linspace(0,10,4)
c

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [52]:
c = np.linspace(0,2*np.pi,10)  # 10 angles between 0 an d2pi leaneraly spaced
c

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [53]:
# np.logspace
d = np.logspace(0,4,3)   # start exponent, stop exponent, number of values
d

array([1.e+00, 1.e+02, 1.e+04])

In [61]:
e = np.zeros(5)
print(e)
ee = np.zeros(5, dtype=np.bool_)
print(ee)

[0. 0. 0. 0. 0.]
[False False False False False]


In [59]:
f = np.ones(4, dtype=np.int64) # creat array ofones with an integer data type
f

array([1, 1, 1, 1])

In [63]:
g = np.ones(6)
print(g)
print(g.shape)
g.shape = (2,3)       # manipulate the shape
print(g)
print(g.shape)

[1. 1. 1. 1. 1. 1.]
(6,)
[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [64]:
k = np.arange(100,1000,100)
print(k)
print(k.size)
print(k.shape)

[100 200 300 400 500 600 700 800 900]
9
(9,)


In [69]:
print(k[0])
print(k[-1])
print(k[0:4:2])
print(k[3:1:-1])
print(k[3:])

100
900
[100 300]
[400 300]
[400 500 600 700 800 900]


# two dimensional arrays

In [70]:
m = np.arange(1,13,1)
print(m)
m.shape=(3,4)      # make sure to use = to set shape
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
# pull out row 1 column 0
print(m[0,0])
print(m[1,2])

1
7


In [80]:
print(m[:,1])    # pull out col
print(m[2:,])    # pull out row
print()
print(m[1:,2:])
print()
print(m[1:,1:3])
print()
print()

[ 2  6 10]
[[ 9 10 11 12]]

[[ 7  8]
 [11 12]]

[[ 6  7]
 [10 11]]




In [81]:
#np.where to find location of a value
n = np.arange(-3,4,1)
print(n)

[-3 -2 -1  0  1  2  3]


In [85]:
print(np.where(n==2))
print(n[5])

loc = np.where(n==2)
print(n[loc])

(array([5]),)
2
[2]


In [88]:
loc = np.where(n>0)
print(loc)
print(n[loc])

(array([4, 5, 6]),)
[1 2 3]


In [90]:
p = np.array([1,1,2,2])
loc = np.where(p==1)
print(loc)
print(p[loc])

(array([0, 1]),)
[1 1]


In [92]:
# np.where can be used to remove outliers from data sets
r = np.array([2.2,2.1,2.3,2.0,-9999999999999])
locs = np.where(r>0)
r[locs]

array([2.2, 2.1, 2.3, 2. ])

# Boolean Masks

when masking each true returns a value where as false returns nothing

In [93]:
t = np.array([-3,-4,0,10,15])
mask1 = np.array([False,False,False,True,True])
t[mask1]

array([10, 15])

In [101]:
mask2 = t>2
print(mask2)
print(t[mask2])
print()
mask3 = t<=0
print(mask3)
print(t[mask3])

[False False False  True  True]
[10 15]

[ True  True  True False False]
[-3 -4  0]


In [104]:
t = np.array([0,1,2,3,4,5])
x = 2*t**2 + 4*4 - 10
print(x)

[ 6  8 14 24 38 56]


In [107]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(b - a)
print(np.cross(a,b))
print(np.dot(a,b))

[5 7 9]
[3 3 3]
[-3  6 -3]
32
